name: Check for new release and build Zen Browser

on:
  schedule:
    - cron: '0 0 * * *'  # Run once a day at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-for-new-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get the latest release from Zen Browser
        id: get_latest_release
        run: |
          # Fetch the latest release from Zen Browser repo
          latest_release=$(curl -s https://api.github.com/repos/zen-browser/desktop/releases/latest)
          tag_name=$(echo $latest_release | jq -r '.tag_name')
          echo "tag_name=$tag_name" >> $GITHUB_ENV  # Store the tag name in the environment variable

      - name: Check if the release exists locally
        id: check_local_tag
        run: |
          # Check if the release already exists as a Git tag locally
          if git tag -l "$tag_name" > /dev/null 2>&1; then
            echo "Release $tag_name already exists locally. Skipping build."
            exit 0  # Exit early if the tag exists
          fi
          echo "No matching release found. Proceeding with build."  # Only prints if the tag does not exist

      - name: Grant execution permissions to build script
        run: chmod +x ./zenmake_for_dev.sh  # Ensure the build script is executable

      - name: Run the build script to create release
        if: success()  # Proceed only if the release was not found locally
        run: |
          ./zenmake_for_dev.sh  # Run the build script

      - name: Set up GitHub CLI authentication
        run: |
          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Create release on GitHub and upload assets
        if: success()  # Proceed only if the build was successful
        run: |
          # Use GitHub CLI to create the release and upload the assets
          gh release create "$tag_name" zen-linux-portable.zip zen-windows-portable.zip zen-portable.zip \
          --title "Zen Browser $tag_name" --notes "Automated build for release $tag_name" --repo $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass the built-in GitHub token for authentication
