name: Check for Zen Browser New Release and Build

# This job runs on a schedule every day at midnight
on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight UTC
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  check-for-new-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check for new release from Zen Browser
        id: get_latest_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/zen-browser/desktop/releases/latest)
          echo "Latest release: $latest_release"
          tag_name=$(echo $latest_release | jq -r '.tag_name')
          echo "tag_name=$tag_name" >> $GITHUB_ENV

      - name: Check if this release was already built
        id: check_if_built
        run: |
          # Check if the release already exists in the current repo
          if [[ "$(git tag -l "$tag_name")" != "" ]]; then
            echo "Release $tag_name already exists. Skipping build."
            exit 0  # Skip the build
          fi
          echo "No matching release found. Proceeding with build."

      - name: Run the build script to create release
        if: success()  # Proceed if no previous build was found
        run: |
          # Run the build script to generate releases
          ./zenmake_for_dev.sh  # Your existing build script

      - name: Create release in this repo
        if: success()
        run: |
          # Upload .zip files to this repo's release section
          gh release create "$tag_name" zen-linux-portable.zip zen-windows-portable.zip zen-portable.zip --title "Zen Browser $tag_name" --notes "Automated build for release $tag_name"
